###check user list
GET http://localhost:5000/admin/users/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOlsiYWRtaW4iXSwiaWF0IjoxNzE0MjMzNzEyLCJleHAiOjE3MTQyMzQ2MTJ9.wjdQMHKpWMDWRdFuRSz6YbQLxLQMlGT9PbLsK8fCG8Y

###check specific user's comments
GET http://localhost:5000/users/2/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOlsiYWRtaW4iXSwiaWF0IjoxNzE1MjgyODIzLCJleHAiOjE3MTUyODM3MjN9.OTuD1Gcz-kqaAGU2FHYzCr7q8AyT_zj4ddM-m6E9SHo

### check access token,refresh token
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username":"admin",
    "password":"password"
}

### tests whether the user can see the posts and if their token is valid
GET http://localhost:5000/topics/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOlsiYWRtaW4iXSwiaWF0IjoxNzE0MjMzNzEyLCJleHAiOjE3MTQyMzQ2MTJ9.wjdQMHKpWMDWRdFuRSz6YbQLxLQMlGT9PbLsK8fCG8Y


### check if you can view a certain topic with its comments
GET http://localhost:5000/topics/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOlsiYWRtaW4iXSwiaWF0IjoxNzE1MjgyNzA3LCJleHAiOjE3MTUyODM2MDd9.0KaEHKeINY32Xf1Bu9x0Mtx8lq7hJdI0qX39nWwGkJ4

### ability to add comments to a topic
POST http://localhost:5000/topics/2/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOlsiYWRtaW4iXSwiaWF0IjoxNzE1MzY5NjQzLCJleHAiOjE3MTUzNzA1NDN9.yj5R6qv5Lg1akWA_ge9rWFAs5JLyFQ6KJN3Zfe_CAf8

{
      "content": "testing notification"
}
#### subscribe to a topic
POST http://localhost:5000/topics/2/subscribe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOlsiYWRtaW4iXSwiaWF0IjoxNzE1MjgzNjQ0LCJleHAiOjE3MTUyODQ1NDR9.iKYl0aUNdql82N3V95LuzIk03idI6HftCx2kl7juuMU

#### creates new access tokents
POST http://localhost:5000/auth/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjFiZGFlZGQ1OWQ1ZmJjYTgxNmM5YjYiLCJpZCI6MiwidXNlcm5hbWUiOiJFc3p1IiwibmFtZSI6IkVzenRlciBKb28iLCJwYXNzd29yZCI6IiQyYiQxMCQ0dFRLZlYwQWlLN3lUbk9BZDNGL1pPQy82by5talRBLkhlZFR6UHl4VTBHdEtNbFF4NURUaSIsImlhdCI6MTcxMzM3MzM0Mn0.mdv2RBUrYcMMEIF_nCqWDHx53c91djkDEO7aX1wYvzM"
}
###deletes their refresh token
DELETE http://localhost:5000/auth/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjFiZGFlZGQ1OWQ1ZmJjYTgxNmM5YjYiLCJpZCI6MiwidXNlcm5hbWUiOiJFc3p1IiwibmFtZSI6IkVzenRlciBKb28iLCJwYXNzd29yZCI6IiQyYiQxMCQ0dFRLZlYwQWlLN3lUbk9BZDNGL1pPQy82by5talRBLkhlZFR6UHl4VTBHdEtNbFF4NURUaSIsImlhdCI6MTcxMzM3MzM0Mn0.mdv2RBUrYcMMEIF_nCqWDHx53c91djkDEO7aX1wYvzM"
}